### ISSUE TITLE
Changes for v0.02

### ISSUE THREAD

**Issue by ammaraziz** [ammaraziz/ctgap#1]
- [x] Use scrubby for human removal step
- [x] Filter for chlamydia spp
- [x] Add fastp for adapter and quality trimming
- [x] Collate coverage stats from `samtools coverage`, compute meanmapq for each genome hit.
- [ ] get uniquely mapped reads for `ct_ref.fasta` alignment
- [ ] use top hit reference for 
     - [ ] alignment based genome assembly
     - [ ] denovo assembly
- [x] replace spades with shovill 
- [ ] look at genome completeness for the alignment step

**Comment by gokeson** [comment]
Hurts my head, but that is what you do, isn't it? HAHAHAHAHA

**Comment by gokeson** [comment]
> * [ ]  Use scrubby for human removal step

I can't seem to get scrubby installed via Conda. I have raised an issue on scrubby's GitHub page. Until the issue is resolved, I can do it manually by performing only kraken2 host reads extraction.

**Comment by ammaraziz** [comment]
See my comment on the github page about how to install `scrubby`. 

>  get uniquely mapped reads for ct_ref.fasta alignment

Can you please create a unique set of references for this?

**Comment by ammaraziz** [comment]
It's okay if you want to test independent tools but we should aim to update the pipeline as we go along.

**Comment by gokeson** [comment]
> See my comment on the github page about how to install `scrubby`.
> 
> > get uniquely mapped reads for ct_ref.fasta alignment
> 
> Can you please create a unique set of references for this?
[Ct_refs.zip](https://github.com/ammaraziz/skip/files/12617622/Ct_refs.zip)

I have got four representative genotypes here. I have some more work to do here on getting the best references to use for each body site but that will wait as it is part of another project that I am doing. Yes, the other project is comparing all Ct reference genomes and creating the best consensus sequence for each strain. For this I am using Illumina, nanopore to sequence all reference strains and then some historical 454 gap-closed genomes that the lab currently has. 

For now, I think we can proceed with the four reference strains that I have included in the attached file as they are quite unique genotypes... quite different from each other (see below).
![4RefComp](https://github.com/ammaraziz/skip/assets/144859166/7b1de746-998f-499f-aee0-0be2f169c454)

**Comment by gokeson** [comment]
> * [ ]  replace spades with shovill
I think, according to the documentation, shovill only works well on isolates. Most of the samples I envisaged this pipeline will be used for will be clinical samples which will most likely be metagenomes thus making shovill not very fit for purpose??

**Comment by ammaraziz** [comment]
Most of these have been completed or we've changed course.
